apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend-backend
  template:
    metadata:
      labels:
        app: frontend-backend
    spec:
      containers:
        - name: frontend-container
          image: our-frontend
          ports:
            - containerPort: 8080
        - name: backend-container
          image: our-backend
          ports:
            - containerPort: 9000