name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Build Backend
        run: cd backend && go build
      - name: Build Frontend
        run: cd frontend && go build

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Test Frontend
      run: cd frontend && go test

  Docker-image:
    name: Build & Upload Docker Image
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build Docker Frontend 
        run: chmod +x ci/docker-build-frontend.sh && ci/docker-build-frontend.sh 
        
      - name: Push Docker Frontend
        run: chmod +x ci/docker-push-frontend.sh && ci/docker-push-frontend.sh
        
      - name: Build Docker Backend 
        run: chmod +x ci/docker-build-backend.sh && ci/docker-build-backend.sh 
        
      - name: Push Docker Backend
        run: chmod +x ci/docker-push-backend.sh && ci/docker-push-backend.sh

  Kubernetes-deploy:
    name: Kubernetes deploy
    runs-on: ubuntu-latest

    needs: [Docker-image]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - run: ls
      
      - name: Deploy Frontend Deployment
        run: kubectl --kubeconfig kubeconfig apply -f simple-fortune/frontend-deployment.yaml

      - name: Deplpy Frontend Service
        run: kubectl --kubeconfig kubeconfig apply -f simple-fortune/frontend-service.yaml

      - name: Deploy Backend Deployment
        run: kubectl --kubeconfig kubeconfig apply -f simple-fortune/backend-deployment.yaml

      - name: Deploy Backend Service
        run: kubectl --kubeconfig kubeconfig apply -f simple-fortune/backend-service.yaml