name: Go
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Build Backend
        run: cd backend && go build
      - name: Build Frontend
        run: cd frontend && go build

  Test:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Test Frontend
      run: cd frontend && go test

  Docker-image:
    name: Build & Upload Docker Image
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Build Docker 
        run: chmod +x ci/docker-build-backend.sh && ci/docker-build-frontend.sh 
        
      - name: Push Docker 
        run: chmod +x ci/docker-push-backend.sh && ci/docker-push-frontend.sh
        
