name: Deploy Application

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: self-hosted  # Make sure to use the label assigned to your GitHub Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Deploy Application
        run: ./deploy-script.sh
