name: Deploy Application

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  deploy:
    runs-on: self-hosted  # Make sure to use the label assigned to your GitHub Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: chmod +x scripts/deploy.sh && script/deploy.sh
